// Code generated by clispec-gen from clispec/v1/clispec.yaml. DO NOT EDIT.
package judge

import (
	"os"
	"time"

	"github.com/spf13/cobra"
)

// Options holds the parsed flag values for the judge command.
type Options struct {
	Absolute bool
	Affected bool
	BaseRef string
	Branch string
	CommitSHA string
	Config string
	FindingsSource string
	Gavelspace string
	JSONOutput bool
	OutputSARIF string
	PRAuthor string
	PRBranch string
	PRNumber int
	PRTitle string
	Project string
	Quick bool
	RequireSubmit bool
	ServerURL string
	Summary bool
	TargetFile string
	Timeout time.Duration
	ServerToken string
}

// RegisterFlags binds all judge flags to the given Options struct.
func RegisterFlags(cmd *cobra.Command, opts *Options) {
	cmd.Flags().BoolVar(&opts.Absolute, "absolute", false, "Evaluate quality gate on total findings, ignoring baseline.")
	cmd.Flags().BoolVar(&opts.Affected, "affected", false, "Analyze only Bazel targets affected by changed files (git diff against default branch). Implies --quick.")
	cmd.Flags().StringVar(&opts.BaseRef, "base-ref", "", "Git ref to diff against when using --affected. Defaults to the project's defaultBranch from gavel.yaml.")
	cmd.Flags().StringVar(&opts.Branch, "branch", "", "Branch name. Auto-detected from git if not provided.")
	cmd.Flags().StringVar(&opts.CommitSHA, "commit", "", "Commit SHA. Auto-detected from git if not provided.")
	cmd.Flags().StringVar(&opts.Config, "config", "", "Path to gavel.yaml. Resolution order: flag value, .gavel/gavel.yaml, gavel.yaml, then defaults to .gavel/gavel.yaml.")
	cmd.Flags().StringVar(&opts.FindingsSource, "findings-source", "", "Findings source: auto, gavel, or rules_lint. Defaults to workspace config value if not set.")
	cmd.Flags().StringVar(&opts.Gavelspace, "gavelspace", "", "Associate analysis with a gavelspace (multi-repo group).")
	cmd.Flags().BoolVar(&opts.JSONOutput, "json", false, "Output results as JSON.")
	cmd.Flags().StringVar(&opts.OutputSARIF, "output-sarif", "", "Write merged SARIF 2.1.0 report to the specified file path.")
	cmd.Flags().StringVar(&opts.PRAuthor, "pr-author", "", "Pull request author.")
	cmd.Flags().StringVar(&opts.PRBranch, "pr-branch", "", "Pull request source branch.")
	cmd.Flags().IntVar(&opts.PRNumber, "pr-number", 0, "Pull request number. Creates or updates PR record on server.")
	cmd.Flags().StringVar(&opts.PRTitle, "pr-title", "", "Pull request title.")
	cmd.Flags().StringVar(&opts.Project, "project", "", "Analyze only the named project. Error if not found in config.")
	cmd.Flags().BoolVarP(&opts.Quick, "quick", "q", false, "Run findings only, skip coverage and architecture checks.")
	cmd.Flags().BoolVar(&opts.RequireSubmit, "require-submit", false, "Exit with error if server submission fails. Default behavior is warn and continue.")
	cmd.Flags().StringVar(&opts.ServerURL, "server", envOrDefault("GAVEL_SERVER_URL", ""), "Gavel server URL for shared baseline and result submission.")
	cmd.Flags().BoolVar(&opts.Summary, "summary", false, "Print only the verdict, delta, and rulings; omit the per-finding list.")
	cmd.Flags().StringVar(&opts.TargetFile, "target-file", "", "File path relative to workspace root. Resolves the owning Bazel package and analyzes only that target. Implies --quick.")
	cmd.Flags().DurationVar(&opts.Timeout, "timeout", 30 * time.Minute, "Maximum time for the entire judge run.")
	cmd.Flags().StringVar(&opts.ServerToken, "token", envOrDefault("GAVEL_TOKEN", ""), "API token for server authentication.")
}

func envOrDefault(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
