// Code generated by clispec-gen from clispec/v1/clispec.yaml. DO NOT EDIT.
package initgavel

import (
	"github.com/spf13/cobra"
)

// Options holds the parsed flag values for the init command.
type Options struct {
	Config string
	Force bool
	From string
}

// RegisterFlags binds all init flags to the given Options struct.
func RegisterFlags(cmd *cobra.Command, opts *Options) {
	cmd.Flags().StringVar(&opts.Config, "config", "", "Path to gavel.yaml. Defaults to .gavel/gavel.yaml.")
	cmd.Flags().BoolVar(&opts.Force, "force", false, "Overwrite existing configuration files.")
	cmd.Flags().StringVar(&opts.From, "from", "", "Path to existing gavel.yaml to re-apply. Implies --force.")
}
