// Code generated by clispec-gen from clispec/v1/clispec.yaml. DO NOT EDIT.
package trends

import (
	"os"

	"github.com/spf13/cobra"
)

// Options holds the parsed flag values for the trends command.
type Options struct {
	Branch      string
	JSONOutput  bool
	Limit       int
	Project     string
	ServerURL   string
	ServerToken string
}

// RegisterFlags binds all trends flags to the given Options struct.
func RegisterFlags(cmd *cobra.Command, opts *Options) {
	cmd.Flags().StringVar(&opts.Branch, "branch", "", "Filter trends to a specific branch.")
	cmd.Flags().BoolVar(&opts.JSONOutput, "json", false, "Output results as JSON.")
	cmd.Flags().IntVar(&opts.Limit, "limit", 10, "Number of recent analysis runs to show. Defaults to 10.")
	cmd.Flags().StringVar(&opts.Project, "project", "", "Project name (required).")
	cmd.Flags().StringVar(&opts.ServerURL, "server", envOrDefault("GAVEL_SERVER_URL", ""), "Gavel server URL.")
	cmd.Flags().StringVar(&opts.ServerToken, "token", envOrDefault("GAVEL_TOKEN", ""), "API token for server authentication.")
}

func envOrDefault(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
