/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a session (log in) */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete the current session (log out) */
        delete: operations["deleteCurrentSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the current user's password
         * @description Verifies `current_password`, sets the new password, and revokes the
         *     current session — the client must log in again with the new password.
         */
        post: operations["changeMyPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's API tokens */
        get: operations["listMyTokens"];
        put?: never;
        /**
         * Create a new API token for the current user
         * @description The plaintext `token` is returned exactly once. Subsequent reads return
         *     only the metadata (id, name, prefix, scopes, dates, status).
         */
        post: operations["createMyToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one of the current user's API tokens */
        delete: operations["deleteMyToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gavelspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gavelspaces */
        get: operations["listGavelspaces"];
        put?: never;
        /** Create a gavelspace (admin only) */
        post: operations["createGavelspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gavelspaces/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gavelspace name (used as identity). */
                name: components["parameters"]["GavelspaceName"];
            };
            cookie?: never;
        };
        /** Get a gavelspace by name */
        get: operations["getGavelspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gavelspaces/{name}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gavelspace name (used as identity). */
                name: components["parameters"]["GavelspaceName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a project in a gavelspace (admin only) */
        post: operations["registerGavelspaceProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gavelspaces/{name}/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gavelspace name (used as identity). */
                name: components["parameters"]["GavelspaceName"];
                project_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a project from a gavelspace (admin only) */
        delete: operations["removeGavelspaceProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["listProjects"];
        put?: never;
        /** Create a project (admin only) */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        /** Get a project by key */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{key}/quality-gate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace the project's quality gate (admin only) */
        put: operations["updateProjectQualityGate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{key}/languages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace the project's declared languages (admin only) */
        put: operations["updateProjectLanguages"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{key}/casefiles": {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        /** List casefiles for a project */
        get: operations["listProjectCaseFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{key}/pleadings": {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        /** List pleadings for a project */
        get: operations["listProjectPleadings"];
        put?: never;
        /** File a new pleading against the project (admin only) */
        post: operations["fileProjectPleading"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{key}/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        /**
         * Get the baseline (last casefile on a branch)
         * @description Returns the fingerprints and architecture-violation IDs from the most
         *     recent case file on the given branch. The CLI uses this to mark a
         *     finding as `new` versus `existing` when judging a new commit.
         */
        get: operations["getProjectBaseline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pleadings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pleadings (filterable)
         * @description Cross-project read of the pleadings index. Use `project_id`,
         *     `gavelspace`, and `status` to scope.
         */
        get: operations["listPleadings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pleadings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PleadingID"];
            };
            cookie?: never;
        };
        /** Get a pleading by ID */
        get: operations["getPleading"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Resolve a pleading (admin only) */
        patch: operations["resolvePleading"];
        trace?: never;
    };
    "/casefiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List case files (filterable)
         * @description Cross-project read of the case-file index. At least one of `project_id`
         *     or `gavelspace` is recommended for sensible page sizes; passing
         *     neither lists every case file the caller can see.
         */
        get: operations["listCaseFiles"];
        put?: never;
        /**
         * Open a case file
         * @description First step of the two-step submit flow. Creates an empty case file
         *     attached to the given project at the given commit. Each subsequent
         *     `POST /casefiles/{id}/evidence` call appends evidence; the verdict
         *     is computed when classify + judge run (today done implicitly after
         *     the final evidence upload — see `final` on the evidence endpoint).
         */
        post: operations["createCaseFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/casefiles/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CaseFileID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append one evidence to a case file
         * @description Second step of the two-step submit flow. Uploads a single piece of
         *     evidence to the named case file. Findings, coverage, license and
         *     architecture payloads share the same envelope; the `subtype` field
         *     plus the populated content sub-object determine the kind.
         *
         *     The CLI parses SARIF / LCOV / archtest output locally and posts a
         *     JSON DTO here. Future binary-blob upload variants will live at a
         *     separate endpoint to keep this one's contract small.
         */
        post: operations["ingestCaseFileEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/casefiles/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CaseFileID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize a case file
         * @description Third step of the two-step submit flow. Classify findings against
         *     the project's default-branch baseline (skipped when the case file
         *     was opened with `fresh_evaluation: true`) and run the quality
         *     gate. Returns the verdict + counters; the case file is judged
         *     once and the response is what the CLI surfaces to the user.
         *
         *     Calling finalize twice on the same case file returns a 409
         *     because the aggregate refuses to be judged twice.
         */
        post: operations["finalizeCaseFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/casefiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CaseFileID"];
            };
            cookie?: never;
        };
        /** Get a case file by ID */
        get: operations["getCaseFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List findings across projects (filterable)
         * @description Read-only access to the findings index. Use `project_id`,
         *     `casefile_id`, `gavelspace`, and the metadata filters
         *     (`tool`, `severity`, `status`, `file_path`) to scope the result.
         *     Every parameter is optional.
         */
        get: operations["listFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross-resource search */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{key}/source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        /**
         * Fetch a source-blob from a commit
         * @description Returns the raw contents of `path` at `commit` for the given project.
         *     The server picks an appropriate `Content-Type` for common text
         *     extensions (json/html/plain). Binaries are returned as
         *     `application/octet-stream`.
         */
        get: operations["getProjectSource"];
        put?: never;
        /**
         * Upload source files for a commit
         * @description Bulk-upload source files so the UI can display code context for
         *     findings. Each file is stored keyed by `(project, commit, path)`.
         *     Duplicate uploads are silently ignored (idempotent).
         *     Only files referenced by findings need to be uploaded.
         */
        post: operations["uploadProjectSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a user (admin only) */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Error envelope per RFC 7807. `type` is a URI reference that callers
         *     can switch on; `title` is a short human-readable phrase.
         */
        Problem: {
            /**
             * Format: uri-reference
             * @example about:blank
             */
            type: string;
            title: string;
            /** Format: int32 */
            status: number;
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
        };
        Health: {
            /**
             * @description Always `ok` when the endpoint responds.
             * @enum {string}
             */
            status: "ok";
        };
        Me: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @enum {string} */
            role: "admin" | "maintainer" | "viewer";
            /** Format: uuid */
            tenant_id: string;
            must_change_password: boolean;
        };
        LoginRequest: {
            /** @description Tenant slug. Defaults to the server's bootstrap tenant. */
            tenant?: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
        };
        CreateTokenRequest: {
            /** @description Human-readable label for this token. */
            name: string;
            scopes: ("ingest" | "admin")[];
            /**
             * @description When omitted the token never expires. Capped at the server's
             *     configured maximum (default 365).
             */
            expires_in_days?: number;
        };
        /**
         * @description Plaintext `token` is returned exactly once at creation time. Store it
         *     somewhere safe — the server only keeps a SHA-256 hash.
         */
        CreatedToken: {
            /** Format: uuid */
            id: string;
            name: string;
            scopes: string[];
            /** @description Full plaintext token. Shown once. */
            token: string;
            /**
             * @description First few characters of the token. Surfaced in listings so users
             *     can identify which token they are looking at.
             */
            prefix: string;
        };
        TokenSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            prefix: string;
            scopes: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            is_revoked: boolean;
            is_expired: boolean;
        };
        TokenList: {
            items: components["schemas"]["TokenSummary"][];
            /**
             * @description Opaque cursor for the next page, or `null` when the caller has
             *     reached the end.
             */
            next_cursor: string | null;
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            display_name: string;
            /** Format: password */
            password: string;
            /**
             * @default viewer
             * @enum {string}
             */
            role: "admin" | "maintainer" | "viewer";
        };
        CreatedUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "maintainer" | "viewer";
        };
        /** @description Summary view returned in lists. */
        Gavelspace: {
            name: string;
            /** Format: int32 */
            project_count: number;
            /** Format: date-time */
            created_at: string;
        };
        GavelspaceDetail: {
            name: string;
            projects: components["schemas"]["GavelspaceProject"][];
            /** Format: date-time */
            created_at: string;
        };
        /** @description Project registered in a gavelspace. */
        GavelspaceProject: {
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            latest_verdict: string;
        };
        GavelspaceList: {
            items: components["schemas"]["Gavelspace"][];
            next_cursor: string | null;
        };
        CreateGavelspaceRequest: {
            name: string;
        };
        CreatedGavelspace: {
            name: string;
        };
        RegisterGavelspaceProjectRequest: {
            /** Format: uuid */
            project_id: string;
            /**
             * @description Bazel target pattern this project owns inside the gavelspace
             *     (e.g. `//apps/server/...`). Must be unique within the
             *     gavelspace.
             */
            target_pattern: string;
        };
        /** @description Project summary as returned in lists. */
        Project: {
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            default_branch: string;
            latest_verdict: string;
            /** Format: int32 */
            total_findings: number;
            /** Format: date-time */
            created_at: string;
        };
        ProjectDetail: {
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            default_branch: string;
            latest_verdict: string;
            /** Format: int32 */
            total_findings: number;
            /** Format: date-time */
            created_at: string;
            target_pattern: string;
            languages: string[];
            quality_gate_rules: components["schemas"]["ProjectRuleView"][];
            severity_counts: {
                [key: string]: number;
            };
        };
        ProjectRuleView: {
            subtype: string;
            strategy_type: string;
        };
        ProjectList: {
            items: components["schemas"]["Project"][];
            next_cursor: string | null;
        };
        CreateProjectRequest: {
            key: string;
            name: string;
            target_pattern?: string;
        };
        CreatedProject: {
            /** Format: uuid */
            project_id: string;
        };
        /** @description Replacement payload for a project's quality-gate rules. */
        QualityGate: {
            rules: components["schemas"]["QualityGateRule"][];
        };
        QualityGateRule: {
            subtype: string;
            strategy: components["schemas"]["QualityGateStrategy"];
            /**
             * Format: int32
             * @description Minimum findings or violations that must be resolved per cycle.
             */
            min_resolved?: number;
            /**
             * Format: double
             * @description Minimum coverage percentage change required (e.g. 0 = must not decrease).
             */
            min_delta?: number;
        };
        /**
         * @description Strategy union. Exactly one of the optional fields must be set
         *     according to `type`.
         */
        QualityGateStrategy: {
            /** @enum {string} */
            type: "count_by_severity" | "zero_tolerance" | "min_percentage" | "forbidden_list" | "max_violations" | "min_new_code_coverage";
            count_by_severity?: components["schemas"]["CountBySeverityStrategy"];
            min_percentage?: components["schemas"]["MinPercentageStrategy"];
            forbidden_list?: components["schemas"]["ForbiddenListStrategy"];
            max_violations?: components["schemas"]["MaxViolationsStrategy"];
            min_new_code_coverage?: components["schemas"]["MinNewCodeCoverageStrategy"];
        };
        CountBySeverityStrategy: {
            /** Format: int32 */
            max_error: number;
            /** Format: int32 */
            max_warning: number;
            /** Format: int32 */
            max_note: number;
        };
        MinPercentageStrategy: {
            /** Format: double */
            min: number;
        };
        ForbiddenListStrategy: {
            forbidden: string[];
        };
        MaxViolationsStrategy: {
            /** Format: int32 */
            max: number;
        };
        MinNewCodeCoverageStrategy: {
            /** Format: double */
            min: number;
        };
        UpdateLanguagesRequest: {
            languages: string[];
        };
        /** @description Case-file summary as returned in lists. */
        CaseFile: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            commit_sha: string;
            branch: string;
            /** Format: date-time */
            started_at: string;
            verdict_outcome: string;
            /** Format: int32 */
            total_findings: number;
            /** Format: int32 */
            new_findings: number;
            /** Format: int32 */
            existing_findings: number;
            /** Format: int32 */
            resolved_findings: number;
            /** Format: double */
            coverage_percent?: number | null;
            /** Format: date-time */
            created_at: string;
        };
        CaseFileDetail: components["schemas"]["CaseFile"] & {
            evidences: components["schemas"]["Evidence"][];
            rulings: components["schemas"]["Ruling"][];
        };
        Evidence: {
            /** Format: uuid */
            id: string;
            subtype: string;
            source: string;
            /** Format: date-time */
            collected_at: string;
        };
        Ruling: {
            subtype: string;
            passed: boolean;
            detail: string;
        };
        CaseFileList: {
            items: components["schemas"]["CaseFile"][];
            next_cursor: string | null;
        };
        Finding: {
            tool: string;
            rule_id: string;
            severity: string;
            file_path: string;
            /** Format: int32 */
            line: number;
            message: string;
            fingerprint: string;
            status: string;
            source: string;
            commit_sha: string;
            project_key: string;
            /** Format: uuid */
            casefile_id: string;
        };
        FindingList: {
            items: components["schemas"]["Finding"][];
            next_cursor: string | null;
        };
        Baseline: {
            fingerprints: string[];
            architecture_ids: string[];
            has_previous: boolean;
        };
        FinalizeCaseFileRequest: {
            verdict: components["schemas"]["Verdict"];
            counters: components["schemas"]["AnalysisCounters"];
        };
        Pleading: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: int32 */
            number: number;
            title: string;
            petitioner: string;
            source_branch: string;
            target_branch: string;
            commit_sha: string;
            /** @enum {string} */
            status: "open" | "merged" | "closed";
            gate_result?: components["schemas"]["GateResult"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        GateResult: {
            passed: boolean;
            conditions?: components["schemas"]["GateCondition"][];
        };
        GateCondition: {
            label: string;
            operator: string;
            value: string;
            threshold: string;
            passed: boolean;
        };
        PleadingList: {
            items: components["schemas"]["Pleading"][];
            next_cursor: string | null;
        };
        FilePleadingRequest: {
            /** Format: int32 */
            number: number;
            title: string;
            petitioner: string;
            source_branch: string;
            target_branch: string;
            commit_sha: string;
        };
        FiledPleading: {
            /** Format: uuid */
            pleading_id: string;
        };
        ResolvePleadingRequest: {
            /** @enum {string} */
            outcome: "merged" | "closed";
        };
        SearchResult: {
            type: string;
            id: string;
            title: string;
            subtitle: string;
            url: string;
        };
        SearchResults: {
            results: components["schemas"]["SearchResult"][];
        };
        UploadSourceRequest: {
            /** @description Full commit SHA the files belong to. */
            commit: string;
            /** @description Source files to store. Maximum 500 per request. */
            files: components["schemas"]["SourceFile"][];
        };
        SourceFile: {
            /** @description Repository-relative file path. */
            path: string;
            /** @description UTF-8 file contents. */
            content: string;
        };
        CreateCaseFileRequest: {
            /** Format: uuid */
            project_id: string;
            commit_sha: string;
            branch: string;
            /**
             * Format: date-time
             * @description Optional explicit start time. Defaults to the server's `Now()`
             *     when omitted, which is normally what the CLI wants.
             */
            started_at?: string;
            /**
             * @description When true, the eventual judge step skips classify against the
             *     project's default branch — useful when the quality gate just
             *     changed and prior fingerprints are no longer comparable.
             */
            fresh_evaluation?: boolean;
        };
        CreatedCaseFile: {
            /** Format: uuid */
            case_file_id: string;
        };
        /**
         * @description Single evidence upload. Exactly one of the content sub-fields
         *     (`findings`, `coverage`, `new_code_coverage`, `license`,
         *     `architecture`) must be populated according to `subtype`.
         */
        IngestEvidenceRequest: {
            /**
             * @description Optional client-supplied evidence identifier. When omitted the
             *     server mints one. Useful when the client wants to retry the
             *     upload idempotently.
             */
            id?: string;
            /** @enum {string} */
            subtype: "code_quality" | "coverage" | "new_code_coverage" | "license" | "architecture" | "source";
            /** @description Tool or origin that produced the evidence (e.g. `golangci-lint`). */
            source: string;
            /** Format: date-time */
            collected_at: string;
            findings?: components["schemas"]["IngestFinding"][] | null;
            coverage?: components["schemas"]["IngestCoverage"];
            new_code_coverage?: components["schemas"]["IngestNewCodeCoverage"];
            license?: components["schemas"]["IngestLicense"];
            architecture?: components["schemas"]["IngestArchitecture"];
        };
        IngestedEvidence: {
            /** Format: uuid */
            evidence_id: string;
        };
        IngestFinding: {
            tool: string;
            rule_id: string;
            severity: string;
            file_path: string;
            /** Format: int32 */
            line: number;
            message: string;
            fingerprint: string;
        };
        IngestCoverage: {
            /** Format: int32 */
            total_lines: number;
            /** Format: int32 */
            covered_lines: number;
            by_language?: components["schemas"]["IngestLanguageStats"][];
            by_file?: components["schemas"]["IngestFileCoverage"][] | null;
        };
        IngestLanguageStats: {
            language: string;
            /** Format: int32 */
            total_lines: number;
            /** Format: int32 */
            covered_lines: number;
        };
        IngestNewCodeCoverage: {
            /** Format: int32 */
            covered_lines: number;
            /** Format: int32 */
            coverable_lines: number;
        };
        IngestLicense: {
            dependencies: components["schemas"]["IngestDependency"][];
        };
        IngestDependency: {
            name: string;
            version: string;
            license: string;
        };
        IngestArchitecture: {
            violations: components["schemas"]["IngestViolation"][];
        };
        IngestViolation: {
            rule: string;
            source_pkg: string;
            target_pkg: string;
            message: string;
        };
        FinalizedCaseFile: {
            /** Format: uuid */
            case_file_id: string;
            verdict: components["schemas"]["Verdict"];
            counters: components["schemas"]["AnalysisCounters"];
        };
        Verdict: {
            /** @enum {string} */
            outcome: "pass" | "fail" | "warning";
            rulings?: components["schemas"]["Ruling"][];
            /** Format: date-time */
            evaluated_at: string;
        };
        AnalysisCounters: {
            /** Format: int32 */
            findings_count: number;
            /** Format: double */
            coverage_percent: number;
            /** Format: int32 */
            new_count: number;
            /** Format: int32 */
            existing_count: number;
            /** Format: int32 */
            resolved_count: number;
            has_tracking: boolean;
        };
        IngestFileCoverage: {
            file_path: string;
            covered_lines: number[];
            uncovered_lines: number[];
        };
        FileCoverageData: {
            covered_lines: number[];
            uncovered_lines: number[];
        };
        SourceWithContext: {
            /** @description UTF-8 file contents. */
            content: string;
            coverage?: components["schemas"]["FileCoverageData"];
            findings?: components["schemas"]["Finding"][] | null;
        };
    };
    responses: {
        /** @description Request body is malformed or violates an invariant. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description No valid credentials were presented. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Caller is authenticated but lacks the required role. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The requested resource does not exist or is not visible to the caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Credentials were presented but rejected. */
        InvalidCredentials: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The supplied `current_password` does not match the stored hash. */
        CurrentPasswordIncorrect: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
        Limit: number;
        /** @description Opaque cursor returned by the previous page's `next_cursor`. */
        Cursor: string;
        /** @description Gavelspace name (used as identity). */
        GavelspaceName: string;
        /** @description Project key (slug; used as identity). */
        ProjectKey: string;
        PleadingID: string;
        CaseFileID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session created. Sets a `gavel_session` HttpOnly cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["InvalidCredentials"];
        };
    };
    deleteCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted. Clears the `gavel_session` cookie. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changeMyPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed. Session has been revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["CurrentPasswordIncorrect"];
        };
    };
    listMyTokens: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens sorted by `created_at` desc. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createMyToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenRequest"];
            };
        };
        responses: {
            /** @description Token created. Plaintext returned once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedToken"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not allowed to mint a token with the requested scopes. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteMyToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Token does not belong to the current user. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listGavelspaces: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gavelspaces, sorted by `created_at` desc. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GavelspaceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGavelspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGavelspaceRequest"];
            };
        };
        responses: {
            /** @description Gavelspace created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedGavelspace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Gavelspace with that name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getGavelspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gavelspace name (used as identity). */
                name: components["parameters"]["GavelspaceName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gavelspace detail including registered projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GavelspaceDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    registerGavelspaceProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gavelspace name (used as identity). */
                name: components["parameters"]["GavelspaceName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterGavelspaceProjectRequest"];
            };
        };
        responses: {
            /** @description Project registered. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description Target pattern conflicts with another project already registered
             *     in this gavelspace.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    removeGavelspaceProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gavelspace name (used as identity). */
                name: components["parameters"]["GavelspaceName"];
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects, sorted by `created_at` desc. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedProject"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Project with that key already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProjectQualityGate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualityGate"];
            };
        };
        responses: {
            /** @description Quality gate updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProjectLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLanguagesRequest"];
            };
        };
        responses: {
            /** @description Languages updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listProjectCaseFiles: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Casefiles, sorted by `started_at` desc. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFileList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listProjectPleadings: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
                status?: "open" | "merged" | "closed";
            };
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pleadings, sorted by `created_at` desc. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PleadingList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    fileProjectPleading: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilePleadingRequest"];
            };
        };
        responses: {
            /** @description Pleading filed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiledPleading"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getProjectBaseline: {
        parameters: {
            query?: {
                /**
                 * @description Branch to read the baseline for. Defaults to the project's
                 *     `default_branch`.
                 */
                branch?: string;
            };
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Baseline payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Baseline"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listPleadings: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
                project_id?: string;
                gavelspace?: string;
                status?: "open" | "merged" | "closed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pleadings, sorted by `created_at` desc. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PleadingList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getPleading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PleadingID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pleading detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pleading"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    resolvePleading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PleadingID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolvePleadingRequest"];
            };
        };
        responses: {
            /** @description Pleading resolved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCaseFiles: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
                project_id?: string;
                gavelspace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case files, sorted by `started_at` desc. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFileList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createCaseFile: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Opaque key supplied by the client to deduplicate a retried
                 *     POST. Repeating the call with the same key + same payload
                 *     within the server's idempotency window returns the original
                 *     response. Stripe-style semantics.
                 */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaseFileRequest"];
            };
        };
        responses: {
            /** @description Case file opened. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedCaseFile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    ingestCaseFileEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CaseFileID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestEvidenceRequest"];
            };
        };
        responses: {
            /** @description Evidence ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestedEvidence"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    finalizeCaseFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CaseFileID"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FinalizeCaseFileRequest"];
            };
        };
        responses: {
            /** @description Verdict computed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizedCaseFile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Case file is already judged. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getCaseFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CaseFileID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case file detail with evidence summaries and rulings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseFileDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listFindings: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous page's `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
                project_id?: string;
                casefile_id?: string;
                gavelspace?: string;
                tool?: string;
                severity?: string;
                status?: string;
                file_path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Findings index page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    search: {
        parameters: {
            query?: {
                q?: string;
                /** @description Maximum number of items to return. Defaults to 50, capped at 200. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mixed search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProjectSource: {
        parameters: {
            query: {
                commit: string;
                path: string;
                /**
                 * @description When present, the response switches from raw binary to a JSON
                 *     envelope that includes the file content plus coverage and findings
                 *     for the given case-file analysis run.
                 */
                casefile?: string;
            };
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Without `casefile`: raw file contents (any MIME type).
             *     With `casefile`: JSON envelope with source, coverage, and findings.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                    "application/json": components["schemas"]["SourceWithContext"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadProjectSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project key (slug; used as identity). */
                key: components["parameters"]["ProjectKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSourceRequest"];
            };
        };
        responses: {
            /** @description All files stored successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Email already in use. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
