// Code generated by clispec-gen from clispec/v1/clispec.yaml. DO NOT EDIT.
package projects

import (
	"github.com/spf13/cobra"
)

// Options holds the parsed flag values for the projects command.
type Options struct {
	Config string
}

// RegisterFlags binds all projects flags to the given Options struct.
func RegisterFlags(cmd *cobra.Command, opts *Options) {
	cmd.Flags().StringVar(&opts.Config, "config", "", "Path to gavel.yaml.")
}
